# --- !Ups

create table JOBQUEUE (
  ID integer generated by default as identity(start with 1) not null primary key,
  NAME varchar not null,
  DESCRIPTION varchar null,
  STATUS varchar null);


insert into JOBQUEUE (NAME, DESCRIPTION, STATUS) values ('Job 1', 'some description', 'Completed');
insert into JOBQUEUE (NAME, DESCRIPTION, STATUS) values ('Bear', 'another description', 'In Progress');
insert into JOBQUEUE (NAME, DESCRIPTION, STATUS) values ('Cat', 'mode askdasd asdad', 'In Progress');
insert into JOBQUEUE (NAME, DESCRIPTION, STATUS) values ('Dog', 'asda asda sdasd','Waiting');

create table LOG (
  ID integer generated by default as identity(start with 1) not null primary key,
  JOB_ID integer not null,
  DESCRIPTION varchar null);

insert into LOG (JOB_ID, DESCRIPTION) values (1, 'Action completed');
insert into LOG (JOB_ID, DESCRIPTION) values (2, 'running file');
insert into LOG (JOB_ID, DESCRIPTION) values (3, 'executing task');
insert into LOG (JOB_ID, DESCRIPTION) values (4, 'Starting ....');



# --- !Downs

drop table JOBQUEUE;
drop table LOG;
